### ISSUE TITLE
GPU memory leak during training

### ISSUE THREAD

**Issue by TomWyllie** [tracel-ai/burn#4792]
**Describe the bug**
There is a GPU memory leak affecting model training, causing multiple backends to crash by running out of memory. This occurs in `0.21.0-pre.3` (and the current `main` branch), but does not occur in `0.21.0-pre.2`. 

**To Reproduce**
1. `git checkout v0.21.0-pre.3`
2. Run the CIFAR-10 example, e.g. `cargo run --example custom-image-dataset --release --features wgpu`
3. Observe the memory leak using e.g. `nvtop`, screenshot below (yellow line is GPU memory usage). The memory jumps up at the start of the epoch for both train and validation passes.
4. This usually causes an out of memory panic in the backend, but if you have lots of VRAM you might not run out before training finishes, depending on model size, number of epochs etc.

This issue occurs for me on `0.21.0-pre.3` but not on `0.21.0-pre.2`. I have found the issue happening with backends `wgpu`, `cuda`, and `vulkan` both with this example, and another unrelated image model, on both GTX 1060 3GB and RTX 3060 12 GB GPUs. CPU backends are unaffected.

**Expected behavior**
Expect memory to stay near constant after the dataset loads, and training run not to panic.

**Screenshots**
<img width="1098" height="400" alt="Image" src="https://github.com/user-attachments/assets/43e175d2-d81d-4f2b-8772-2a86ea2ec634" />

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - Burn Version `0.21.0-pre.3`
 - CUDA version: observed with 13.0 and 13.2

**Additional context**
I have tried bisecting the issue on the burn main branch and resolved that at `3cd6e90e4` there was no issue, but by `6cb763107` there was an issue. I couldn't resolve inbetween because there was another error which I'm assuming was due to mismatch between burn/cube branches. It's possible that this is an issue with memory pooling in CubeCL but I'm not sure. I don't know if this issue is architecture specific, but I have only tested on 2x image related networks.

I have found this issue happening on `dev` and `release` profiles, as well as with/without features `fusion` / `autotune` enabled.

**Comment by nathanielsimard** [comment]
I found that when using a single stream with setting `max_streams = 1`, there is no more memory leaks. I think with multiple streams, some workload during training is sent to different streams during training which doesn't play nice with memory pools.

**Comment by TomWyllie** [comment]
Nice thank you, this is a workaround that fixes my setup for the time being. I wasn't using a `cubecl.toml` already but adding
```
[streaming]
max_streams = 1
```
to `cubecl.toml` in the same directory has the VRAM is staying constant so far so presumably should be able to train to completion without crashing. I don't know anything about what streams are in CubeCL though 😅

**Comment by nathanielsimard** [comment]
You can also test with different number of streams. Between 2 and 4 is probably better than 1 and it might still be stable regarding memory usage. I'm unsure where the problem originate, but it might be a flushing issue with tasks being created but never accessed.

**Comment by Dreaming-Codes** [comment]
I've also experienced this on the last pre-release and setting max_streams to 1 fixed it. I haven't tried with the stable release yet

**Comment by IvanUkhov** [comment]
I think I ran into the same problem after upgrading from 0.20.1 to 0.21. It just runs out of memory. Reducing the batch size delays the crash, which confirms that there is a memory leak of some sort.

**Comment by laggui** [comment]
Linking #4991 which describes the current issue and plan of action.
